"""phase5 transcripts and notes tables

Revision ID: 9e3404a55c23
Revises: d73602f70688
Create Date: 2026-06-12 09:38:33.052538
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '9e3404a55c23'
down_revision = 'd73602f70688'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conference_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('decisions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gemini_model', sa.String(length=64), nullable=True),
    sa.Column('doc_id', sa.String(length=256), nullable=True),
    sa.Column('doc_url', sa.String(length=1024), nullable=True),
    sa.Column('emailed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_conference_id'), 'notes', ['conference_id'], unique=True)
    op.create_table('transcripts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conference_id', sa.UUID(), nullable=False),
    sa.Column('full_text', sa.LargeBinary(), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('speaker_map', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_conference_id'), 'transcripts', ['conference_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcripts_conference_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_notes_conference_id'), table_name='notes')
    op.drop_table('notes')
    # ### end Alembic commands ###
