"""phase4 event ingestion tables and columns

Revision ID: d73602f70688
Revises: 2abdc7a1f5e6
Create Date: 2026-06-11 10:32:11.462804
"""
from alembic import op
import sqlalchemy as sa


revision = 'd73602f70688'
down_revision = '2abdc7a1f5e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.String(length=256), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('conference_record_name', sa.String(length=256), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_events_message_id'), 'processed_events', ['message_id'], unique=True)
    op.create_table('conferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=True),
    sa.Column('oauth_connection_id', sa.UUID(), nullable=False),
    sa.Column('conference_record_name', sa.String(length=256), nullable=False),
    sa.Column('transcript_resource_name', sa.String(length=256), nullable=True),
    sa.Column('actual_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pipeline_state', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['oauth_connection_id'], ['oauth_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conferences_conference_record_name'), 'conferences', ['conference_record_name'], unique=True)
    op.create_index(op.f('ix_conferences_meeting_id'), 'conferences', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_conferences_oauth_connection_id'), 'conferences', ['oauth_connection_id'], unique=False)
    op.create_index(op.f('ix_conferences_pipeline_state'), 'conferences', ['pipeline_state'], unique=False)
    op.create_table('event_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('oauth_connection_id', sa.UUID(), nullable=False),
    sa.Column('subscription_name', sa.String(length=512), nullable=False),
    sa.Column('expire_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('last_renewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['oauth_connection_id'], ['oauth_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_subscriptions_expire_time'), 'event_subscriptions', ['expire_time'], unique=False)
    op.create_index(op.f('ix_event_subscriptions_oauth_connection_id'), 'event_subscriptions', ['oauth_connection_id'], unique=True)
    op.add_column('meetings', sa.Column('meet_space_name', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_meetings_meet_space_name'), 'meetings', ['meet_space_name'], unique=False)
    op.add_column('oauth_connections', sa.Column('google_user_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_connections', 'google_user_id')
    op.drop_index(op.f('ix_meetings_meet_space_name'), table_name='meetings')
    op.drop_column('meetings', 'meet_space_name')
    op.drop_index(op.f('ix_event_subscriptions_oauth_connection_id'), table_name='event_subscriptions')
    op.drop_index(op.f('ix_event_subscriptions_expire_time'), table_name='event_subscriptions')
    op.drop_table('event_subscriptions')
    op.drop_index(op.f('ix_conferences_pipeline_state'), table_name='conferences')
    op.drop_index(op.f('ix_conferences_oauth_connection_id'), table_name='conferences')
    op.drop_index(op.f('ix_conferences_meeting_id'), table_name='conferences')
    op.drop_index(op.f('ix_conferences_conference_record_name'), table_name='conferences')
    op.drop_table('conferences')
    op.drop_index(op.f('ix_processed_events_message_id'), table_name='processed_events')
    op.drop_table('processed_events')
    # ### end Alembic commands ###
